[package]
name = "hermit-rs-template"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_os = "hermit")'.dependencies]
hermit = { version =  "0.8", path = "/Users/lsw/Code/hermit/hermit-rs/hermit"} 
